# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labelwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LabelerWindow(object):
    def setupUi(self, LabelerWindow):
        LabelerWindow.setObjectName("LabelerWindow")
        LabelerWindow.resize(823, 890)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        LabelerWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("qr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LabelerWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(LabelerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setObjectName("tabs")
        self.tInventory = QtWidgets.QWidget()
        self.tInventory.setObjectName("tInventory")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tInventory)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.tInventory)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.lblSubtitle = QtWidgets.QLabel(self.widget)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.gridLayout.addWidget(self.lblSubtitle, 3, 0, 1, 1)
        self.lblTitle = QtWidgets.QLabel(self.widget)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout.addWidget(self.lblTitle, 2, 0, 1, 1)
        self.frType = QtWidgets.QFrame(self.widget)
        self.frType.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frType.setObjectName("frType")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frType)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbNamed = QtWidgets.QPushButton(self.frType)
        self.pbNamed.setCheckable(True)
        self.pbNamed.setChecked(True)
        self.pbNamed.setAutoExclusive(True)
        self.pbNamed.setObjectName("pbNamed")
        self.horizontalLayout.addWidget(self.pbNamed)
        self.pbSerial = QtWidgets.QPushButton(self.frType)
        self.pbSerial.setCheckable(True)
        self.pbSerial.setAutoExclusive(True)
        self.pbSerial.setObjectName("pbSerial")
        self.horizontalLayout.addWidget(self.pbSerial)
        self.gridLayout.addWidget(self.frType, 0, 0, 1, 2)
        self.lblCategory = QtWidgets.QLabel(self.widget)
        self.lblCategory.setObjectName("lblCategory")
        self.gridLayout.addWidget(self.lblCategory, 1, 0, 1, 1)
        self.leTitle = QtWidgets.QLineEdit(self.widget)
        self.leTitle.setObjectName("leTitle")
        self.gridLayout.addWidget(self.leTitle, 2, 1, 1, 1)
        self.leSubtitle = QtWidgets.QLineEdit(self.widget)
        self.leSubtitle.setObjectName("leSubtitle")
        self.gridLayout.addWidget(self.leSubtitle, 3, 1, 1, 1)
        self.lblDescription = QtWidgets.QLabel(self.widget)
        self.lblDescription.setObjectName("lblDescription")
        self.gridLayout.addWidget(self.lblDescription, 4, 0, 1, 2)
        self.leCategory = QtWidgets.QLineEdit(self.widget)
        self.leCategory.setObjectName("leCategory")
        self.gridLayout.addWidget(self.leCategory, 1, 1, 1, 1)
        self.teDescription = QtWidgets.QPlainTextEdit(self.widget)
        self.teDescription.setObjectName("teDescription")
        self.gridLayout.addWidget(self.teDescription, 5, 0, 1, 2)
        self.verticalLayout.addWidget(self.widget)
        self.tabs.addTab(self.tInventory, "")
        self.tText = QtWidgets.QWidget()
        self.tText.setObjectName("tText")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tText)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.tText)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.lePlainText = QtWidgets.QLineEdit(self.tText)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.lePlainText.setFont(font)
        self.lePlainText.setObjectName("lePlainText")
        self.verticalLayout_3.addWidget(self.lePlainText)
        spacerItem1 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.tabs.addTab(self.tText, "")
        self.verticalLayout_2.addWidget(self.tabs)
        self.gbLabelFormat = QtWidgets.QGroupBox(self.centralwidget)
        self.gbLabelFormat.setObjectName("gbLabelFormat")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbLabelFormat)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pbNormalSingle = QtWidgets.QPushButton(self.gbLabelFormat)
        self.pbNormalSingle.setMinimumSize(QtCore.QSize(360, 120))
        self.pbNormalSingle.setStyleSheet(":checked { background-color: blue; }")
        self.pbNormalSingle.setIconSize(QtCore.QSize(325, 100))
        self.pbNormalSingle.setCheckable(True)
        self.pbNormalSingle.setChecked(True)
        self.pbNormalSingle.setAutoExclusive(True)
        self.pbNormalSingle.setObjectName("pbNormalSingle")
        self.gridLayout_2.addWidget(self.pbNormalSingle, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.gbLabelFormat)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.gbLabelFormat)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.pbHighDurabilitySingle = QtWidgets.QPushButton(self.gbLabelFormat)
        self.pbHighDurabilitySingle.setMinimumSize(QtCore.QSize(360, 120))
        self.pbHighDurabilitySingle.setStyleSheet(":checked { background-color: blue; }")
        self.pbHighDurabilitySingle.setText("")
        self.pbHighDurabilitySingle.setIconSize(QtCore.QSize(325, 95))
        self.pbHighDurabilitySingle.setCheckable(True)
        self.pbHighDurabilitySingle.setChecked(False)
        self.pbHighDurabilitySingle.setAutoExclusive(True)
        self.pbHighDurabilitySingle.setObjectName("pbHighDurabilitySingle")
        self.gridLayout_2.addWidget(self.pbHighDurabilitySingle, 3, 0, 1, 1)
        self.pbHighDurabilityDouble = QtWidgets.QPushButton(self.gbLabelFormat)
        self.pbHighDurabilityDouble.setMinimumSize(QtCore.QSize(360, 120))
        self.pbHighDurabilityDouble.setStyleSheet(":checked { background-color: blue; }")
        self.pbHighDurabilityDouble.setText("")
        self.pbHighDurabilityDouble.setIconSize(QtCore.QSize(325, 95))
        self.pbHighDurabilityDouble.setShortcut("")
        self.pbHighDurabilityDouble.setCheckable(True)
        self.pbHighDurabilityDouble.setChecked(False)
        self.pbHighDurabilityDouble.setAutoExclusive(True)
        self.pbHighDurabilityDouble.setObjectName("pbHighDurabilityDouble")
        self.gridLayout_2.addWidget(self.pbHighDurabilityDouble, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gbLabelFormat)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 1, 1, 1)
        self.pbNormalDouble = QtWidgets.QPushButton(self.gbLabelFormat)
        self.pbNormalDouble.setMinimumSize(QtCore.QSize(360, 120))
        self.pbNormalDouble.setStyleSheet(":checked { background-color: blue; }")
        self.pbNormalDouble.setText("")
        self.pbNormalDouble.setIconSize(QtCore.QSize(325, 100))
        self.pbNormalDouble.setShortcut("")
        self.pbNormalDouble.setCheckable(True)
        self.pbNormalDouble.setChecked(False)
        self.pbNormalDouble.setAutoExclusive(True)
        self.pbNormalDouble.setObjectName("pbNormalDouble")
        self.gridLayout_2.addWidget(self.pbNormalDouble, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gbLabelFormat)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gbLabelFormat)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbLabelFormat)
        self.gbPrint = QtWidgets.QGroupBox(self.centralwidget)
        self.gbPrint.setObjectName("gbPrint")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbPrint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sbLabels = QtWidgets.QSpinBox(self.gbPrint)
        self.sbLabels.setMinimum(1)
        self.sbLabels.setMaximum(20)
        self.sbLabels.setObjectName("sbLabels")
        self.gridLayout_3.addWidget(self.sbLabels, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gbPrint)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(5)
        self.line_2.setMidLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 2, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.gbPrint)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gbPrint)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 3)
        self.lblOutputCount = QtWidgets.QLabel(self.gbPrint)
        self.lblOutputCount.setObjectName("lblOutputCount")
        self.gridLayout_3.addWidget(self.lblOutputCount, 1, 0, 1, 3)
        self.pbReset = QtWidgets.QPushButton(self.gbPrint)
        self.pbReset.setObjectName("pbReset")
        self.gridLayout_3.addWidget(self.pbReset, 4, 2, 1, 1)
        self.pbPrint = QtWidgets.QPushButton(self.gbPrint)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pbPrint.setFont(font)
        self.pbPrint.setObjectName("pbPrint")
        self.gridLayout_3.addWidget(self.pbPrint, 4, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.gbPrint)
        LabelerWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LabelerWindow)
        self.statusbar.setObjectName("statusbar")
        LabelerWindow.setStatusBar(self.statusbar)
        self.lblSubtitle.setBuddy(self.leSubtitle)
        self.lblTitle.setBuddy(self.leTitle)
        self.lblCategory.setBuddy(self.leCategory)
        self.lblDescription.setBuddy(self.teDescription)

        self.retranslateUi(LabelerWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LabelerWindow)
        LabelerWindow.setTabOrder(self.tabs, self.pbNamed)
        LabelerWindow.setTabOrder(self.pbNamed, self.pbSerial)
        LabelerWindow.setTabOrder(self.pbSerial, self.leCategory)
        LabelerWindow.setTabOrder(self.leCategory, self.leTitle)
        LabelerWindow.setTabOrder(self.leTitle, self.leSubtitle)
        LabelerWindow.setTabOrder(self.leSubtitle, self.teDescription)
        LabelerWindow.setTabOrder(self.teDescription, self.lePlainText)
        LabelerWindow.setTabOrder(self.lePlainText, self.pbNormalSingle)
        LabelerWindow.setTabOrder(self.pbNormalSingle, self.pbNormalDouble)
        LabelerWindow.setTabOrder(self.pbNormalDouble, self.pbHighDurabilitySingle)
        LabelerWindow.setTabOrder(self.pbHighDurabilitySingle, self.pbHighDurabilityDouble)

    def retranslateUi(self, LabelerWindow):
        _translate = QtCore.QCoreApplication.translate
        LabelerWindow.setWindowTitle(_translate("LabelerWindow", "Daniel\'s LABEL-O-MATIC 2000™"))
        self.lblSubtitle.setText(_translate("LabelerWindow", "Subtitle:"))
        self.lblTitle.setText(_translate("LabelerWindow", "Title:"))
        self.pbNamed.setText(_translate("LabelerWindow", "N&amed"))
        self.pbSerial.setText(_translate("LabelerWindow", "&Serial"))
        self.lblCategory.setText(_translate("LabelerWindow", "Category:"))
        self.leTitle.setPlaceholderText(_translate("LabelerWindow", "Llama"))
        self.leSubtitle.setPlaceholderText(_translate("LabelerWindow", "The Fuzziest"))
        self.lblDescription.setText(_translate("LabelerWindow", "Description:"))
        self.leCategory.setPlaceholderText(_translate("LabelerWindow", "Animal"))
        self.teDescription.setPlaceholderText(_translate("LabelerWindow", "Lama glama, camelid, very cute, wow fuzzy"))
        self.tabs.setTabText(self.tabs.indexOf(self.tInventory), _translate("LabelerWindow", "&Inventory Label"))
        self.label.setText(_translate("LabelerWindow", "Labels created as \"Plain Text\" will not create inventory, nor will they have a QR code."))
        self.lePlainText.setPlaceholderText(_translate("LabelerWindow", "FRAGILE"))
        self.tabs.setTabText(self.tabs.indexOf(self.tText), _translate("LabelerWindow", "Plain &Text"))
        self.gbLabelFormat.setTitle(_translate("LabelerWindow", "Sticker Format: You must put that sticker roll in the printer! (choose one):"))
        self.pbNormalSingle.setToolTip(_translate("LabelerWindow", "Standard sticker, one label per sticker"))
        self.label_2.setText(_translate("LabelerWindow", "Standard sticker, one label per sticker"))
        self.pbHighDurabilitySingle.setToolTip(_translate("LabelerWindow", "High-durability sticker, one label per sticker"))
        self.pbHighDurabilityDouble.setToolTip(_translate("LabelerWindow", "High-durability sticker, two labels per sticker"))
        self.label_3.setText(_translate("LabelerWindow", "Standard sticker, two labels per sticker"))
        self.pbNormalDouble.setToolTip(_translate("LabelerWindow", "Standard sticker, two labels per sticker"))
        self.label_4.setText(_translate("LabelerWindow", "High-durability sticker, one label per sticker"))
        self.label_5.setText(_translate("LabelerWindow", "High-durability sticker, two labels per sticker"))
        self.gbPrint.setTitle(_translate("LabelerWindow", "Print Setup:"))
        self.label_6.setText(_translate("LabelerWindow", "# of labels:"))
        self.label_7.setText(_translate("LabelerWindow", "Does the label printer have the desired sticker roll inside? If so:"))
        self.lblOutputCount.setText(_translate("LabelerWindow", "OUTPUT COUNT"))
        self.pbReset.setText(_translate("LabelerWindow", "&Reset"))
        self.pbPrint.setText(_translate("LabelerWindow", "&Print Now!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LabelerWindow = QtWidgets.QMainWindow()
    ui = Ui_LabelerWindow()
    ui.setupUi(LabelerWindow)
    LabelerWindow.show()
    sys.exit(app.exec_())
